import fs from "fs";

const categories: Record<string, string[]> = {
  fruits: [
    "Apple",
    "Pear",
    "Mango",
    "Papaya",
    "Strawberry",
    "Cherry",
    "Peach",
    "Plum",
    "Banana",
    "Plantain",
    "Orange",
    "Tangerine",
    "Kiwi",
    "Guava",
    "Pineapple",
    "Coconut",
    "Lemon",
    "Lime",
    "Apricot",
    "Nectarine",
    "Grapes",
    "Blueberries",
    "Blackberry",
    "Raspberry",
    "Lychee",
    "Longan",
    "Fig",
    "Pomegranate",
    "Watermelon",
    "Muskmelon",
    "Dragonfruit",
    "Passionfruit",
    "Starfruit",
    "Jackfruit",
    "Guava",
    "Custard Apple",
    "Sapota",
    "Mulberry",
  ],

  animals: [
    "Lion",
    "Tiger",
    "Leopard",
    "Cheetah",
    "Dog",
    "Wolf",
    "Fox",
    "Hyena",
    "Cat",
    "Panther",
    "Horse",
    "Donkey",
    "Zebra",
    "Cow",
    "Buffalo",
    "Goat",
    "Sheep",
    "Deer",
    "Moose",
    "Rabbit",
    "Hare",
    "Eagle",
    "Falcon",
    "Crow",
    "Raven",
    "Shark",
    "Dolphin",
    "Whale",
    "Orca",
    "Snake",
    "Lizard",
    "Frog",
    "Toad",
    "Camel",
    "Giraffe",
    "Elephant",
    "Bear",
    "Panda",
    "Kangaroo",
    "Penguin",
    "Ostrich",
    "Peacock",
    "Parrot",
    "Sparrow",
    "Hen",
    "Rooster",
  ],

  countries: [
    "India",
    "Pakistan",
    "USA",
    "Canada",
    "France",
    "Italy",
    "Germany",
    "Netherlands",
    "Spain",
    "Portugal",
    "Brazil",
    "Argentina",
    "China",
    "Japan",
    "Australia",
    "New Zealand",
    "Nepal",
    "Bhutan",
    "Russia",
    "Ukraine",
    "Mexico",
    "Colombia",
    "Egypt",
    "Morocco",
    "Sweden",
    "Norway",
    "Greece",
    "Turkey",
    "Thailand",
    "Vietnam",
    "Malaysia",
    "Indonesia",
    "Philippines",
    "South Korea",
    "North Korea",
    "Saudi Arabia",
    "UAE",
    "Iran",
    "Iraq",
    "Israel",
    "Poland",
    "Belgium",
    "Switzerland",
  ],

  food: [
    "Burger",
    "Sandwich",
    "Pizza",
    "Pasta",
    "Biryani",
    "Pulao",
    "Noodles",
    "Spaghetti",
    "Samosa",
    "Kachori",
    "Idli",
    "Dosa",
    "Tacos",
    "Burritos",
    "Cake",
    "Pastry",
    "Chocolate",
    "Candy",
    "Tea",
    "Coffee",
    "Milk",
    "Juice",
    "Paneer",
    "Tofu",
    "Soup",
    "Stew",
    "Fries",
    "Chips",
    "Hotdog",
    "Sub",
    "Ice Cream",
    "Kulfi",
    "Brownie",
    "Muffin",
    "Donut",
    "Cupcake",
  ],

  sports: [
    "Cricket",
    "Baseball",
    "Football",
    "Rugby",
    "Basketball",
    "Netball",
    "Tennis",
    "Badminton",
    "Hockey",
    "Ice Hockey",
    "Kabaddi",
    "Kho Kho",
    "Boxing",
    "Wrestling",
    "Golf",
    "Polo",
    "Chess",
    "Checkers",
    "Swimming",
    "Diving",
    "Cycling",
    "Skating",
    "Volleyball",
    "Handball",
    "Archery",
    "Shooting",
    "Karate",
    "Judo",
    "Surfing",
    "Skiing",
    "Formula 1",
    "MotoGP",
  ],

  professions: [
    "Doctor",
    "Nurse",
    "Teacher",
    "Professor",
    "Engineer",
    "Architect",
    "Lawyer",
    "Judge",
    "Police",
    "Detective",
    "Pilot",
    "Captain",
    "Chef",
    "Baker",
    "Actor",
    "Director",
    "Singer",
    "Dancer",
    "Farmer",
    "Gardener",
    "Driver",
    "Conductor",
    "Plumber",
    "Electrician",
    "Writer",
    "Poet",
    "Photographer",
    "Painter",
    "Soldier",
    "Commander",
    "Scientist",
    "Businessman",
    "Entrepreneur",
    "Designer",
    "Tailor",
  ],

  dailyObjects: [
    "Chair",
    "Table",
    "Sofa",
    "Bed",
    "Pillow",
    "Blanket",
    "Cup",
    "Glass",
    "Plate",
    "Spoon",
    "Fork",
    "Knife",
    "Bottle",
    "Bucket",
    "Fan",
    "AC",
    "TV",
    "Remote",
    "Mobile",
    "Laptop",
    "Watch",
    "Clock",
    "Pen",
    "Pencil",
    "Notebook",
    "Book",
    "Bag",
    "Wallet",
    "Shoes",
    "Slippers",
    "Helmet",
    "Mirror",
    "Comb",
    "Toothbrush",
    "Soap",
    "Shampoo",
  ],
};

// Generate many pairs by random grouping
function generateLargePairs(words: string[], targetPairs: number) {
  const pairs: [string, string][] = [];
  const shuffled = [...words].sort(() => Math.random() - 0.5);

  let index = 0;
  while (pairs.length < targetPairs) {
    const word1 = shuffled[index % shuffled.length];
    const word2 = shuffled[(index + 1) % shuffled.length];

    if (word1 !== word2) {
      pairs.push([word1, word2]);
    }

    index += 2;
  }

  return pairs;
}

const finalPairs: Record<string, [string, string][]> = {};
const pairsPerCategory = 220; // 7 categories × 220 = 1540 pairs

Object.entries(categories).forEach(([category, words]) => {
  finalPairs[category] = generateLargePairs(words, pairsPerCategory);
});

fs.writeFileSync(
  "generatedWordPairs.json",
  JSON.stringify(finalPairs, null, 2),
);

console.log("1500+ word pairs generated successfully.");
